conj_present = {
    # "ukan": {
    #     "1s": "dut",
    #     "3s": "du",
    #     "1p": "dugu",
    #     "2s": "duzu",
    #     "2p": "duzue",
    #     "3p": "dute",
    # },
    "izan": {
        "1s": "naiz",
        "3s": "da",
        "1p": "gara",
        "2s": "zara",
        "2p": "zarete",
        "3p": "dira",
    },
    "egon": {
        "1s": "nago",
        "3s": "dago",
        "1p": "gaude",
        "2s": "zaude",
        "2p": "zaudete",
        "3p": "daude",
    },
    "joan": {
        "1s": "noa",
        "3s": "doa",
        "1p": "goaz",
        "2s": "zoaz",
        "2p": "zoazte",
        "3p": "doaz",
    },
    "ibili": {
        "1s": "nabil",
        "2s": "zabiltza",
        "3s": "dabil",
        "1p": "gabiltza",
        "2p": "zabiltzate",
        "3p": "dabiltza",
    },
    "etorri": {
        "1s": "nator",
        "2s": "zatoz",
        "3s": "dator",
        "1p": "gatoz",
        "2p": "zatozte",
        "3p": "datoz",
    },
}
conj_past = {
    # "ukan": {
    #     "1s": "nuen",
    #     "2s": "zenuen",
    #     "3s": "zuen",
    #     "1p": "genuen",
    #     "2p": "zenuten",
    #     "3p": "zuten",
    # },
    "izan": {
        "1s": "nintzen",
        "2s": "zinen",
        "3s": "zen",
        "1p": "ginen",
        "2p": "zineten",
        "3p": "ziren",
    },
    "egon": {
        "1s": "nengoen",
        "2s": "zeunden",
        "3s": "zegoen",
        "1p": "geunden",
        "2p": "zeundeten",
        "3p": "zeuden",
    },
    "ibili": {
        "1s": "nenbilen",
        "2s": "zenbiltzan",
        "3s": "zebilen",
        "1p": "genbiltzan",
        "2p": "zenbiltzaten",
        "3p": "zebiltzan",
    },
    "etorri": {
        "1s": "nentorren",
        "2s": "zentozen",
        "3s": "zetorren",
        "1p": "gentozen",
        "2p": "zentozten",
        "3p": "zetozten",
    },
    "joan": {
        "1s": "nindoan",
        "2s": "zindiazen",
        "3s": "zihoan",
        "1p": "gindoazen",
        "2p": "zindoazten",
        "3p": "zihoazen",
    },
}
